### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by oliviathevampire** [ewanhowell5195/MinecraftTitleTextures#16]
Hi! I'm just wondering, in the compile script, where is it you define that it should draw the ABC thing?

**Comment by ewanhowell5195** [comment]
It does everything

**Comment by oliviathevampire** [comment]
Ye I understood that, but I wanna make it render some more letters, and unsure where I would edit to do that

**Comment by ewanhowell5195** [comment]
No. All thumbnails will be the same, don’t change it.

**Comment by oliviathevampire** [comment]
So it will break them or? Like I understand that they might probably get wider or something, but will anything else break?

**Comment by ewanhowell5195** [comment]
No, I want them to be consistent

**Comment by oliviathevampire** [comment]
Consistent between the different textures? Or consistent with something else?

**Comment by ewanhowell5195** [comment]
Every thumbnail will look the same, with the only difference wing the texture used.

**Comment by oliviathevampire** [comment]
Would it not change everyone if I ran the compile script? so they would be the same but with more letters?

**Comment by ewanhowell5195** [comment]
I do t want that, I want it to stay how it is, can you just leave it alone and not change it

**Comment by oliviathevampire** [comment]
Ok, Ok, I was only gonna do it for my fork, was not even gonna make a PR but sure

**Comment by ewanhowell5195** [comment]
If you are adding textures, why not make a pr to add them to the actual plugin?

**Comment by oliviathevampire** [comment]
May in the future but rn just playing around
